# Generated by Django 5.1.3 on 2025-01-12 01:09

import django.core.validators
import flower_shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0004_order_address_order_comment_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Элемент корзины', 'verbose_name_plural': 'Элементы корзины'},
        ),
        migrations.RemoveField(
            model_name='report',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='report',
            name='order',
        ),
        migrations.RemoveField(
            model_name='report',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='report',
            name='sales_data',
        ),
        migrations.AddField(
            model_name='report',
            name='period_end',
            field=models.DateField(default=flower_shop.models.default_period_end, verbose_name='Конец периода'),
        ),
        migrations.AddField(
            model_name='report',
            name='period_start',
            field=models.DateField(default=flower_shop.models.default_period_start, verbose_name='Начало периода'),
        ),
        migrations.AddField(
            model_name='report',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество заказов'),
        ),
        migrations.AddField(
            model_name='report',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая выручка'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
    ]
