# Generated by Django 5.1.3 on 2025-01-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0005_alter_cartitem_options_remove_report_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Код привязки'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram ID'),
        ),
    ]
