# Generated by Django 5.1.3 on 2025-01-12 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0006_user_link_code_user_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
