# Generated by Django 5.1.3 on 2025-01-13 02:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0008_alter_product_price_alter_report_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_changed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения статуса'),
        ),
    ]
