# Generated by Django 5.1.3 on 2025-01-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0010_remove_order_status_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят к работе'), ('in_progress', 'Находится в работе'), ('in_delivery', 'В доставке'), ('completed', 'Выполнен')], default='accepted', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
