# Generated by Django 5.1.3 on 2025-01-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_secret_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Секретный код администратора'),
        ),
    ]
